spring:
  datasource:
    url: ${env.datasource.url}
    username: ${env.datasource.user}
    password: ${env.datasource.password}
    driverClassName: ${env.datasource.driver}
    hikari:
      schema: ${env.datasource.schema}
  application:
    name: finclusion

  kafka:
    bootstrap-servers: LAPTOP-75RCPK7V:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: finclusion-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  ai:
    api-key: xxx
    model: gemini-2.5-flash
    startup-test-enabled: false
  kafka:
    startup-test-enabled: false
    enabled: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO