spring:
  datasource:
    url: ${env.datasource.url}
    username: ${env.datasource.user}
    password: ${env.datasource.password}
    driverClassName: ${env.datasource.driver}
    hikari:
      schema: ${env.datasource.schema}
  application:
    name: finclusion

app:
  ai:
    api-key: AIzaSyCom4XQ9v7tnKCo6XKlAbSlnU08AjNggVE
    model: gemini-2.5-flash
    startup-test-enabled: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO