spring:
  datasource:
    url: ${env.datasource.url}
    username: ${env.datasource.user}
    password: ${env.datasource.password}
    driverClassName: ${env.datasource.driver}
    hikari:
      schema: ${env.datasource.schema}
  application:
    name: finclusion

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO